# Generated by Django 5.0.3 on 2024-03-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='StudentInfo',
        ),
    ]
